# Site settings
title: Zeikar's Portfolio
email: your-email@example.com
description: >-
  Software Developer Portfolio - 
  Showcasing my projects and development journey
baseurl: ""
url: "https://zeikar.github.io"
twitter_username: zeikar
github_username: zeikar

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# SEO settings
lang: en
author: Zeikar
social:
  name: Zeikar
  links:
    - https://github.com/zeikar

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/